availableMetrics:
- Creator
- Unit
- Characteristic
templates:
  oboe:
    optionalMetrics:
    - Creator
    - Unit
    - Characteristic
  oboeTest:
    optionalMetrics:
    - Creator
    requiredMetrics:
    - Unit